# Database services to be used in development to check
# connectivity, read and write operations.

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - 5432:5432
  mysql:
    image: mysql
    command: --init-file /data/application/mysql_init.sql
    volumes:
      - ./mysql_init.sql:/data/application/mysql_init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - 3306:3306
  mariadb:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - 3307:3306